// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID        pgtype.UUID      `json:"id"`
	TeamID    pgtype.UUID      `json:"team_id"`
	AuthorID  pgtype.UUID      `json:"author_id"`
	Title     string           `json:"title"`
	Content   string           `json:"content"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Team struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type TeamMember struct {
	UserID   pgtype.UUID      `json:"user_id"`
	TeamID   pgtype.UUID      `json:"team_id"`
	Role     string           `json:"role"`
	JoinedAt pgtype.Timestamp `json:"joined_at"`
}

type User struct {
	ID         pgtype.UUID      `json:"id"`
	CognitoSub string           `json:"cognito_sub"`
	Name       string           `json:"name"`
	Email      string           `json:"email"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}
