// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (user_id, team_id, role)
VALUES ($1, $2, $3)
RETURNING user_id, team_id, role, joined_at
`

type AddTeamMemberParams struct {
	UserID uuid.UUID `json:"user_id"`
	TeamID uuid.UUID `json:"team_id"`
	Role   string    `json:"role"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRowContext(ctx, addTeamMember, arg.UserID, arg.TeamID, arg.Role)
	var i TeamMember
	err := row.Scan(
		&i.UserID,
		&i.TeamID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (team_id, author_id, title, content)
VALUES ($1, $2, $3, $4)
RETURNING id, team_id, author_id, title, content, created_at, updated_at
`

type CreateDocumentParams struct {
	TeamID   uuid.UUID `json:"team_id"`
	AuthorID uuid.UUID `json:"author_id"`
	Title    string    `json:"title"`
	Content  string    `json:"content"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.TeamID,
		arg.AuthorID,
		arg.Title,
		arg.Content,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateTeam(ctx context.Context, name string) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam, name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (cognito_sub, name, email)
VALUES ($1, $2, $3)
RETURNING id, cognito_sub, name, email, created_at, updated_at
`

type CreateUserParams struct {
	CognitoSub string `json:"cognito_sub"`
	Name       string `json:"name"`
	Email      string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.CognitoSub, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents 
WHERE id = $1 AND author_id = $2
`

type DeleteDocumentParams struct {
	ID       uuid.UUID `json:"id"`
	AuthorID uuid.UUID `json:"author_id"`
}

func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, arg.ID, arg.AuthorID)
	return err
}

const getUserByCognitoSub = `-- name: GetUserByCognitoSub :one
SELECT id, cognito_sub, name, email, created_at, updated_at FROM users
WHERE cognito_sub = $1 LIMIT 1
`

func (q *Queries) GetUserByCognitoSub(ctx context.Context, cognitoSub string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByCognitoSub, cognitoSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, team_id, author_id, title, content, created_at, updated_at FROM documents
ORDER BY created_at DESC
`

func (q *Queries) ListDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.AuthorID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByTeam = `-- name: ListDocumentsByTeam :many
SELECT id, team_id, author_id, title, content, created_at, updated_at
FROM documents
WHERE team_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDocumentsByTeamParams struct {
	TeamID uuid.UUID `json:"team_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListDocumentsByTeam(ctx context.Context, arg ListDocumentsByTeamParams) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByTeam, arg.TeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.AuthorID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT users.id, users.name, team_members.role, team_members.joined_at
FROM users
JOIN team_members ON users.id = team_members.user_id
WHERE team_members.team_id = $1
ORDER BY team_members.joined_at DESC
`

type ListTeamMembersRow struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Role     string    `json:"role"`
	JoinedAt time.Time `json:"joined_at"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersRow
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET title = $2, content = $3, updated_at = NOW()
WHERE id = $1 AND author_id = $4
RETURNING id, team_id, author_id, title, content, created_at, updated_at
`

type UpdateDocumentParams struct {
	ID       uuid.UUID `json:"id"`
	Title    string    `json:"title"`
	Content  string    `json:"content"`
	AuthorID uuid.UUID `json:"author_id"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocument,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.AuthorID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
