// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"

	uuid "github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (team_id, author_id, title, content)
VALUES ($1, $2, $3, $4)
RETURNING id, team_id, author_id, title, content, created_at, updated_at
`

type CreateDocumentParams struct {
	TeamID   uuid.UUID `json:"team_id"`
	AuthorID uuid.UUID `json:"author_id"`
	Title    string    `json:"title"`
	Content  string    `json:"content"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.TeamID,
		arg.AuthorID,
		arg.Title,
		arg.Content,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateTeam(ctx context.Context, name string) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (cognito_sub, name, email)
VALUES ($1, $2, $3)
RETURNING id, cognito_sub, name, email, created_at, updated_at
`

type CreateUserParams struct {
	CognitoSub string `json:"cognito_sub"`
	Name       string `json:"name"`
	Email      string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.CognitoSub, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByCognitoSub = `-- name: GetUserByCognitoSub :one
SELECT id, cognito_sub, name, email, created_at, updated_at FROM users
WHERE cognito_sub = $1 LIMIT 1
`

func (q *Queries) GetUserByCognitoSub(ctx context.Context, cognitoSub string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByCognitoSub, cognitoSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, team_id, author_id, title, content, created_at, updated_at FROM documents
ORDER BY created_at DESC
`

func (q *Queries) ListDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.AuthorID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByTeam = `-- name: ListDocumentsByTeam :many
SELECT id, team_id, author_id, title, content, created_at, updated_at FROM documents
WHERE team_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDocumentsByTeam(ctx context.Context, teamID uuid.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.AuthorID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
